package com.email.ai;

import com.email.ai.EmailAIProvider;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;  // ✅ correct

import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Duration;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class OllamaEmailProvider implements EmailAIProvider {

    private final WebClient.Builder webClientBuilder;  // ✅ builder instead of WebClient
    private WebClient webClient;                       // actual client
    @Value("${ollama.api.url:http://localhost:11434/api/generate}")
    private String ollamaApiUrl;

    @Value("${ollama.model:codellama}")   // default to codellama
    private String modelName;


    @PostConstruct
    public void init() {
        this.webClient = webClientBuilder.build();
    }

    @Override
    public String getProviderName() {
        return "OLLAMA";
    }

    @Override
    public String generateReply(String prompt) {
        Map<String, Object> body = Map.of(
                "model", modelName,
                "prompt", prompt,
                "stream", false
        );

        String response = webClient.post()
                .uri(ollamaApiUrl)
                .header("Content-Type", "application/json")
                .bodyValue(body)
                .retrieve()
                .bodyToMono(String.class)
                .block(Duration.ofSeconds(60));

        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(response);
            return root.path("response").asText("No response generated by Ollama.");
        } catch (Exception e) {
            return "Error processing Ollama response: " + e.getMessage();
        }
    }
}
